### ISSUE TITLE
AttributeError: function 'VBVMR_MacroButton_IsDirty' not found

### ISSUE THREAD

**Issue by damp11113** [onyx-and-iris/voicemeeter-api-python#4]
```
Traceback (most recent call last):
  File "C:\Users\user\Documents\pythonProject\test208.py", line 1, in <module>
    import voicemeeterlib
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\voicemeeterlib\__init__.py", line 1, in <module>
    from .factory import request_remote_obj as api
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\voicemeeterlib\factory.py", line 16, in <module>
    from .remote import Remote
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\voicemeeterlib\remote.py", line 8, in <module>
    from .cbindings import CBindings
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\voicemeeterlib\cbindings.py", line 9, in <module>
    class CBindings(metaclass=ABCMeta):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\voicemeeterlib\cbindings.py", line 36, in CBindings
    vm_mdirty = libc.VBVMR_MacroButton_IsDirty
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'VBVMR_MacroButton_IsDirty' not found
```

**Comment by onyx-and-iris** [comment]
Hello. Are you using an old version of Voicemeeter? I know that Macrobutton IsDirty wasn't added to the CAPI until later on. This wrapper was tested against the versions listed in the README.

**Comment by onyx-and-iris** [comment]
Closing as non-responsive. You may try updating your Voicemeeter, perhaps it will help. Any further questions feel free to open a new issue.

**Comment by onyx-and-iris** [comment]
This is more a note for myself. Macrobutton functions were present in the C API as far back as 5 years ago:

https://github.com/vburel2018/Voicemeeter-SDK/blob/890e8617811e5df2b3bcc33ae11ca46151a3b713/VoicemeeterRemote.h#L702

I did add checks for macrobutton binds in the CBindings class in response to this issue:

https://github.com/onyx-and-iris/voicemeeter-api-python/blob/48614ab5fa19ff3886452c9b46f0dc384bce6349/voicemeeterlib/cbindings.py#L39

but I think it's time to drop support for such old versions of Voicemeeter.
